# Generated by Django 5.1 on 2024-08-29 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_card',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_card',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.IntegerField(max_length=4)),
                ('father_name', models.CharField(default=None, max_length=100, null=True)),
                ('mother_name', models.CharField(default=None, max_length=100, null=True)),
                ('brother_name', models.CharField(default=None, max_length=100, null=True)),
                ('grandfather_name', models.CharField(default=None, max_length=100, null=True)),
                ('grandmother_name', models.CharField(default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
