# Generated by Django 5.1 on 2024-08-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_aadhar_card_user_pan_card_familydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetails',
            name='total_members',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
