# Generated by Django 5.1 on 2024-08-29 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_familydetails_brother_name_brother_sister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
